# Generated by Django 5.0.6 on 2024-06-18 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('anilist_id', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('cover_art', models.CharField(max_length=150, unique=True)),
                ('total_episodes', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('book_id', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('cover_art', models.CharField(max_length=150, unique=True)),
                ('total_page', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mangadex_id', models.CharField(max_length=150, unique=True)),
                ('anilist_id', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('cover_art', models.CharField(max_length=150, unique=True)),
                ('total_chapters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('ANIME', 'Anime'), ('MANGA', 'Manga'), ('BOOK', 'Book')], max_length=10)),
                ('media_id', models.IntegerField()),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('star_rate', models.IntegerField()),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
